export const GET_UNIVERSITIES = 'SET_DATA';
export const FAILED_DATA_FETCH = 'FAILED_DATA_FETCH';
export const SAVE_UNIVERSITIES = 'SAVE_UNIVERSITIES';

export const ADD_UNIVERSITY = 'ADD_UNIVERSITY';
export const REMOVE_UNIVERSITY = 'REMOVE_UNIVERSITY';
export const UPDATE_UNIVERSITY = 'UPDATE_UNIVERSITY';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_H2H_ROUND = 'UPDATE_H2H_ROUND';

// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';