export const GET_UNIVERSITIES = 'SET_DATA';
export const FAILED_DATA_FETCH = 'FAILED_DATA_FETCH';
export const SAVE_UNIVERSITIES = 'SAVE_UNIVERSITIES';

export const ADD_UNIVERSITY = 'ADD_UNIVERSITY';
export const REMOVE_UNIVERSITY = 'REMOVE_UNIVERSITY';
export const UPDATE_UNIVERSITY = 'UPDATE_UNIVERSITY';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_H2H_ROUND = 'UPDATE_H2H_ROUND';

export const GET_UNIVERSITY_SCORE_LIST = 'GET_UNIVERSITY_SCORE_LIST';
export const GET_INDIVIDUAL_SCORE_LIST = 'GET_INDIVIDUAL_SCORE_LIST';